### PR TITLE
#163083409 Setup and deploy base application to Heroku

### PR DESCRIPTION
**Pull request by kamyaD**
#### What does this PR do?
- Setup and deploy base application to Heroku

#### Description of Task to be completed?
- Create a pipeline
- Create a staging app
- Create a production app
- Create Procfile
- Promote staging app to production in the pipeline 

#### How should this be manually tested?
 - visit the following URL: https://ah-infinity-stones-staging.herokuapp.com/

#### What are the relevant pivotal tracker stories?
[#163083409](https://www.pivotaltracker.com/story/show/163083409)

#### Screenshots
screenshot 2019-01-09 at 17 47 19
screenshot 2019-01-09 at 17 48 12
screenshot 2019-01-09 at 17 48 43

### CODE REVIEW

**Review by PromasterGuru — APPROVED** [review]
Great Job

**Review by leonardnjura — COMMENTED** [review]
Nice progress for us to see the app live on heroku @kamyaD

**Review by ThaDeveloper — APPROVED** [review]
Great Work @kamyaD

**Review by rkemmy — APPROVED** [review]
@kamyaD This is awesome. On behalf of hound, woof!

**Pull request merged**
