### PR TITLE
#161966878 User Comments

### PR DESCRIPTION
**Pull request by leonardnjura**
#### What does this PR do?
- Integrates route to leave comments on articles

#### How should this be manually tested?
`$ git clone -b ft-user-comments-161966878 https://github.com/andela/ah-infinity-stones-frontend`
`$ cd ah-infinity-stones-frontend`
> Install node modules specified in `package.json`
`$ npm install`
`$ npm start`

> Navigate to `~/login` page
> Then Navigate to `~/articles/<slug>/comments` page
> If you are authenticated, now you are ready to add your comment on the article or reply to other comments

#### What are the relevant pivotal tracker stories?
[#161966878](https://www.pivotaltracker.com/story/show/161966878)

#### Screenshots
screen shot 2019-02-01 at 14 56 42

screen shot 2019-02-01 at 14 56 31

### CODE REVIEW

**Review by PromasterGuru — APPROVED** [review]

**Review by PromasterGuru — CHANGES_REQUESTED** [review]
Your Travis is failing, kindly work on that so that your PR can be merged.

**Review by rkemmy — CHANGES_REQUESTED** [review]
There is commented code in some of your files. Please remove it before the PR is merged.

**Review by kamyaD — COMMENTED** [review]
Seams there are merge conflicts sir. Otherwise thank you for the good job

**Review by codeplus254 — APPROVED** [review]
Great work

**Review by PromasterGuru — APPROVED** [review]

**Review by rkemmy — APPROVED** [review]

**Review by kamyaD — APPROVED** [review]

**Pull request merged**
