### PR TITLE
#161966869 Run Code Climate test coverage

### PR DESCRIPTION
**Pull request by PromasterGuru**
#### What does this PR do?
- Runs Code Climate test coverage

#### Description of Task to be completed?
- Integrate Code Climate to GitHub repo
- Add Code Climate maintainability badge
- Add Code Climate test coverage badge

#### What are the relevant pivotal tracker stories?
[#161966869](https://www.pivotaltracker.com/story/show/161966869)

### CODE REVIEW

**Review by leonardnjura — COMMENTED** [review]
Good work @PromasterGuru and add a screenshot or two for those nice badges

**Comment by PromasterGuru** [comment]
Hey @leonardnjura, I have already added three awesome badges.

**Review by rkemmy — CHANGES_REQUESTED** [review]
@PromasterGuru  great job including the maintainability and test coverage badge. Could you include a screenshot of the test coverage as of now because the coverage is currently unknown and there is already a default test. You could try this resource, I hope it's helpful https://www.npmjs.com/package/unit-coverage

**Comment by kamyaD** [comment]
@PromasterGuru I think the task is well done, however it could have been better if you included some screenshots.

**Review by ThaDeveloper — APPROVED** [review]
Good stuff, this PR is OK.

**Comment by PromasterGuru** [comment]
@rkemmy Thank you for your feedback. The coverage report will only be displayed when the default branch sends a payload to codeclimate.com. For now, develop is our default branch and the PR haven't been merged. I hope this link will be helpful in case you need more information [Missing Coverage with TravisCI](https://github.com/codeclimate/test-reporter/issues/341)

**Review by rkemmy — APPROVED** [review]

**Pull request merged**
