### PR TITLE
#163110966 Integrate houndCI to Github 

### PR DESCRIPTION
**Pull request by rkemmy**
#### What does this PR do?
- Integrate houndCI to github repo

#### Description of Task to be completed?
- Connect houndCI to the repo
- Add .hound.yml to the project
- Add hound badge to the repo

#### What are the relevant pivotal tracker stories?
[#163110966](https://www.pivotaltracker.com/story/show/163110966)

### CODE REVIEW

**Review by PromasterGuru — APPROVED** [review]
Great job @rkemmy

**Review by kamyaD — APPROVED** [review]
This is Great.

**Review by ThaDeveloper — CHANGES_REQUESTED** [review]
Good work on setting up Hound(our code will be super world-class). Kindly check the naming of eslintignore file, it should be `.eslintignore` not `eslintignore`

**Comment by rkemmy** [comment]
@ThaDeveloper, I have made the necessary changes. Thanks for pointing that out

**Review by ThaDeveloper — APPROVED** [review]

**Review by johnmutuma5 — CHANGES_REQUESTED** [review]
@rkemmy, can we set it up to ignore import issues like [this one](https://github.com/andela/ah-infinity-stones-frontend/pull/4#discussion_r246693290)??

**Review by codeplus254 — CHANGES_REQUESTED** [review]
What is causing this error?
Parsing error: 'import' and 'export' may appear only with 'sourceType: module'

**Review by codeplus254 — APPROVED** [review]

**Review by johnmutuma5 — APPROVED** [review]

**Pull request merged**
