### PR TITLE
#161966891 Bookmarks Listing 

### PR DESCRIPTION
**Pull request by ThaDeveloper**
#### What does this PR do?
- Implement article bookmarks list

#### Description of Task to be completed?
- Add bookmarks components
- Add API fetch actions
- Hook components with redux store
- add bookmarks listing tests

#### How should this be manually tested?
1. `$ git clone -b ft-list-bookmarks-161966891 https://github.com/andela/ah-infinity-stones-frontend.git`  and `$ cd ah-infinity-stones-frontend`
2. Install the dependencies - `$ npm install`
3. Start the app by running `$ npm start` - This will run the app in the development mode.  
 To test the feature. Open http://localhost:3000/login  to view it in the browser. Provide email and password and click submit. This assumes that you have visited `http://localhost:3000/signup`, created and activated your account.
4. Visit http://localhost:3000/profile  and click `Bookmarks` button. This will list all available article bookmarks for the current user.
4. Test the app by running `$ npm test`
5. Check test coverage by running `$ npm test -- --coverage`

#### What are the relevant pivotal tracker stories?
[#161966891](https://www.pivotaltracker.com/story/show/161966891)

#### Screenshots
screenshot 2019-01-30 at 15 07 12

### CODE REVIEW

**Review by rkemmy — CHANGES_REQUESTED** [review]
Awesome work. Please remove package-lock.json from your tracked files.

**Comment by ThaDeveloper** [comment]
> Awesome work. Please remove package-lock.json from your tracked files.

Seems I picked this from develop as it's in my gitignore.

**Review by PromasterGuru — APPROVED** [review]
Great work

**Review by rkemmy — APPROVED** [review]

**Comment by johnmutuma5** [comment]
@ThaDeveloper, please resolve the merge conflicts.

**Comment by ThaDeveloper** [comment]
> @ThaDeveloper, please resolve the merge conflicts.

@johnmutuma5 It's done

**Pull request merged**
