### PR TITLE
#161966866 Update TravisCI to run tests

### PR DESCRIPTION
**Pull request by PromasterGuru**
#### What does this PR do?
- Update TravisCI to run tests

#### Description of Task to be completed?
- Connect TravisCI to the repo
- Add .travis.yml to the project
- Add TravisCI badge to the repo

#### What are the relevant pivotal tracker stories?
[#161966866](https://www.pivotaltracker.com/story/show/161966866)

### CODE REVIEW

**Review by rkemmy — CHANGES_REQUESTED** [review]
@PromasterGuru Please squash your commits. Great job!

**Comment by PromasterGuru** [comment]
Thanks, @rkemmy, I have worked on that.

**Comment by kamyaD** [comment]
@PromasterGuru  Thanks for the work. Please check on the number of changed files, its showing  Files changed 30,342. Please confirm.

**Review by codeplus254 — CHANGES_REQUESTED** [review]
Kindly add the travisCI badge on the readme so that we can see the build status

**Comment by ThaDeveloper** [comment]
@PromasterGuru Consider adding a trailing blank line at the end of `.travis.yml`, otherwise, this is good.

**Review by codeplus254 — APPROVED** [review]
Great work!

**Review by rkemmy — APPROVED** [review]

**Pull request merged**
